### ISSUE TITLE
Injected Request

### ISSUE THREAD

**Issue by Grafikart** [PHP-DI/Slim-Bridge#20]
Sorry for the title the problem is not easy to summarize

## Problem

Sometimes we want to inject Request into objects 

```php
<?php
namespace Core\Http;

class Request {

    public function __construct(ServerRequestInterface $request)
    {
        $this->request = $request;
        $this->errors = $this->getValidator()->getErrors();
    }

    // ....

}
```

But we receive the "original" request before slim processed it, even if `settings.determineRouteBeforeAppMiddleware` is set to true. 
It would be nice to have a way to get the "processed" request object where slim injected the route attribute.

A solution would be to create a middleware but it forces me to "instantiate" all middleware for every request while type hiting make the middleware instantiated only if the route is reached.

**Comment by mnapoli** [comment]
Hi! This is IMO one of the design flaw in Slim: the request should never get injected because the request is not a dependency, it's a value. It's even more a problem with PSR-7 because the request is immutable (and you experienced that problem as you said). This is a good summary: https://igor.io/2013/03/31/stateless-services.html

So in the end I don't think it's a scenario we should support. Writing a middleware is the best solution.

**Comment by Grafikart** [comment]
Yeah I was trying to think about the architecture and I end up with the same conclusion, middleware (and middleware factory) is the key. Closing this issue.
