### ISSUE TITLE
ControllerInvoker doesn't set request attributes properly

### ISSUE THREAD

**Issue by kuba9392** [PHP-DI/Slim-Bridge#39]
In the ControllerInvoker class there is a issue with request attributes. I can't get attributes from request inside my controller because of that. 

`  $parameters += $request->getAttributes();`

In this part of code getAttributes method returns null.

To solve it you should set attributes from routeArguments and pass new request with attributes to $parameters array.

**Comment by mnapoli** [comment]
Oh the `getAttributes()` method [should always return an array (per the standard)](https://github.com/php-fig/http-message/blob/master/src/ServerRequestInterface.php#L199-L210). However nothing prevents us from casting the `null` to an array (or any other solution that can handle null).

Maybe you could also open an issue on the Slim repository because it seems to be a bug on their side too.

Also how common is this error? Feel free to send a pull request with a test case.

**Comment by Mararok** [comment]
This problem is poorly explained. Its not about `$request->getAttributes()` returns null its about `$request->getAttribute("any_route_defined_placeholder") `returns null because request need set attributes from `$routeArguments` in ControllerInvoker :   

```php
$request = $request->withAttributes($routeArguments);
```

 To solve it I implemented my own slim foundHandler what is decorator on bridge ControllerInvoker class:
https://github.com/SAREhub/microt/blob/master/src/SAREhub/Microt/App/RequestRouteAttributesSetterInvoker.php
And here is injection definition: 
```php
"foundHandler" => create(RequestRouteAttributesSetterInvoker::class)
                ->constructor(create(ControllerInvoker::class)
                    ->constructor(get('foundHandler.invoker')))
```

https://github.com/SAREhub/microt/blob/master/src/SAREhub/Microt/App/BasicContainerConfigurator.php

**Comment by angelxmoreno** [comment]
This is indeed poorly explained but the issue is really the docs.

Given you have a route:
```
$app->get('/books/{id}', ['BooksController','read');
```

To access the value of `id` simply use `$id` as a param:
```php
class BooksController {
    public function read($id) {
        //$id is the attribute
    }
}
```

**Comment by mnapoli** [comment]
If there is no issue here I will close, let me know if that's a mistake.
