### ISSUE TITLE
Php 5.5 support 

### ISSUE THREAD

**Issue by alexandrubeu** [PHP-DI/Slim-Bridge#8]
It seems that this package is supported only by PHP 5.6 and 7. Can you please add support at least for  PHP version 5.5.35

Thank you.

**Comment by mnapoli** [comment]
Hi, PHP 5.5 is going to be maintained only for one more month (http://php.net/supported-versions.php), I understand it might not be easy for you to upgrade but I think today requiring 5.6 isn't too out of place. Especially since this is a rather new package so it targets mostly new projects. Are you trying to add this bridge to an existing project?

**Comment by mdarc** [comment]
I wonder... Why your main dependencies (PHP DI 5/Slim 3) support PHP 5.5 and this extension does not? I know PHP 5.5 is "old" but there is still lots of installations running under that version.

**Comment by mnapoli** [comment]
Because PHP 5.5 is old and will not be supported any longer in a few days. My reasoning was that this bridge would be used for new projects, so new projects are usually started on last versions of PHP.

Given 3 people have already shown interest in PHP 5.5 support, and given this project has a very simple codebase, I'm willing to merge a pull request that applies such changes.

Thanks for the feedback from you 3.

**Comment by danmichaelo** [comment]
PR submitted, I need PHP 5.5 support too. Even though it's a new project I'm working on, I have no influence on the environment where it will run (Ubuntu Trusty with PHP 5.5.9, which I believe is still a fairly common environment).

**Comment by mnapoli** [comment]
Thanks to @danmichaelo a PR was submitted and merged, I have tagged 1.0.2 which supports PHP 5.5.
